apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: game-runner
spec:
  selector:
      matchLabels:
        app: game-runner
  replicas: 3
  template:
    metadata:
      labels:
        app: game-runner
    spec:
      containers:
      - name: game-runner
        image: hemanthcu/matchmaker-game-runner:latest
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq.default
        - name: REDIS_HOST
          value: redis.default
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
---
