apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: matchmaker-rest
spec:
  selector:
      matchLabels:
        app: matchmaker-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: matchmaker-rest
    spec:
      containers:
      - name: matchmaker-rest
        image: hemanthcu/matchmaker-rest:latest
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq.default
        - name: REDIS_HOST
          value: redis.default
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 5000
---
